version: '3.8'

services:
  resep-service:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: resep_db
    volumes:
      - .:/app
    command: npm run dev

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resep_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: